# Generated by Django 6.0.3 on 2026-06-04 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('wu_id', models.CharField(max_length=50, unique=True)),
                ('total_gold_star', models.IntegerField(default=0)),
                ('total_yearly_gold_star', models.IntegerField(default=0)),
                ('last_day_since_gold_star', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MostGoldStarAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('place', models.IntegerField()),
                ('total_gold_stars', models.IntegerField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='most_gold_star_awards', to='scraper.station')),
            ],
        ),
        migrations.CreateModel(
            name='LeastGoldStarAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('place', models.IntegerField()),
                ('total_gold_stars', models.IntegerField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='least_gold_star_awards', to='scraper.station')),
            ],
        ),
        migrations.CreateModel(
            name='HourlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.CharField()),
                ('weather_data', models.JSONField()),
                ('has_gold_star', models.BooleanField(default=False)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_data', to='scraper.station')),
            ],
        ),
        migrations.CreateModel(
            name='HotStreakAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('place', models.IntegerField()),
                ('streak_length', models.IntegerField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_streak_awards', to='scraper.station')),
            ],
        ),
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.CharField()),
                ('has_gold_star', models.BooleanField(default=False)),
                ('gold_star_status', models.CharField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to='scraper.station')),
            ],
        ),
        migrations.CreateModel(
            name='ColdStreakAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('place', models.IntegerField()),
                ('streak_length', models.IntegerField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cold_streak_awards', to='scraper.station')),
            ],
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longest_hot_streak', models.IntegerField(default=0)),
                ('longest_yearly_hot_streak', models.IntegerField(default=0)),
                ('current_hot_streak', models.IntegerField(default=0)),
                ('longest_cold_streak', models.IntegerField(default=0)),
                ('longest_yearly_cold_streak', models.IntegerField(default=0)),
                ('current_cold_streak', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='scraper.station')),
            ],
        ),
    ]
