# Generated by Django 6.0.3 on 2026-03-20 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('wu_id', models.CharField(max_length=50, unique=True)),
                ('wu_link', models.CharField(max_length=200)),
                ('total_gold_star', models.IntegerField(default=0)),
                ('total_yearly_gold_star', models.IntegerField(default=0)),
                ('last_day_since_gold_star', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HourlyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField()),
                ('has_gold_star', models.BooleanField(default=False)),
                ('temp_avg', models.FloatField(blank=True, null=True)),
                ('precip', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_data', to='scraper.station')),
            ],
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longest_gold_star_streak', models.IntegerField(default=0)),
                ('longest_yearly_gold_star_streak', models.IntegerField(default=0)),
                ('current_gold_star_streak', models.IntegerField(default=0)),
                ('longest_cold_streak', models.IntegerField(default=0)),
                ('longest_yearly_cold_streak', models.IntegerField(default=0)),
                ('current_cold_streak', models.IntegerField(default=0)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='scraper.station')),
            ],
        ),
    ]
