# Generated by Django 6.0.3 on 2026-03-20 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hourlydata",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="hourlydata",
            name="station",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hourly_data",
                to="scraper.station",
            ),
        ),
    ]
