# Generated by Django 6.0.3 on 2026-03-21 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_remove_hourlydata_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourlydata',
            name='precip',
        ),
        migrations.RemoveField(
            model_name='hourlydata',
            name='temp_avg',
        ),
    ]
