# Generated by Django 6.0.3 on 2026-03-21 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_remove_hourlydata_precip_remove_hourlydata_temp_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='station',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='scraper.station'),
        ),
    ]
