# Generated by Django 6.0.3 on 2026-03-28 03:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper", "0004_alter_streak_station"),
    ]

    operations = [
        migrations.RenameField(
            model_name="streak",
            old_name="current_gold_star_streak",
            new_name="current_hot_streak",
        ),
        migrations.RenameField(
            model_name="streak",
            old_name="longest_gold_star_streak",
            new_name="longest_hot_streak",
        ),
        migrations.RenameField(
            model_name="streak",
            old_name="longest_yearly_gold_star_streak",
            new_name="longest_yearly_hot_streak",
        ),
        migrations.AddField(
            model_name="station",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="station",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="streak",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="streak",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="hourlydata",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hourly_data",
                to="scraper.station",
            ),
        ),
        migrations.CreateModel(
            name="DailyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recorded_at", models.DateField()),
                ("gold_star_status", models.CharField()),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_data",
                        to="scraper.station",
                    ),
                ),
            ],
        ),
    ]
