services:
  db:
    image: postgres
    container_name: goldstarboard_postgres
    restart: always
    environment:
      POSTGRES_USER: goldstarboard_admin
      POSTGRES_PASSWORD: nogoldforbrandon
      POSTGRES_DB: goldstarboard_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata:
    name: goldstarboard_postgres_volume
