CREATE TABLE "awards" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "awards_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"station_id" varchar NOT NULL,
	"year" integer NOT NULL,
	"title" varchar(50) NOT NULL,
	"type" varchar,
	"rank" integer NOT NULL,
	"score" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "daily_data" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "daily_data_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"station_id" varchar NOT NULL,
	"star_status" varchar,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "historical_stats" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "historical_stats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"station_id" varchar NOT NULL,
	"year" integer NOT NULL,
	"star" integer DEFAULT 0 NOT NULL,
	"hot_streak" integer DEFAULT 0 NOT NULL,
	"cold_streak" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hourly_data" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hourly_data_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"station_id" varchar NOT NULL,
	"metric_data" jsonb NOT NULL,
	"imperial_data" jsonb NOT NULL,
	"status" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(25) NOT NULL,
	"wu_id" varchar(12) NOT NULL UNIQUE,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stats" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stats_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"station_id" varchar NOT NULL,
	"star" integer DEFAULT 0 NOT NULL,
	"hot_streak" integer DEFAULT 0 NOT NULL,
	"cold_streak" integer DEFAULT 0 NOT NULL,
	"last_day_since_star" date,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX "awards_station_id_idx" ON "awards" ("station_id");--> statement-breakpoint
CREATE INDEX "daily_data_station_id_idx" ON "daily_data" ("station_id");--> statement-breakpoint
CREATE INDEX "historical_stats_station_id_idx" ON "historical_stats" ("station_id");--> statement-breakpoint
ALTER TABLE "awards" ADD CONSTRAINT "awards_station_id_stations_wu_id_fkey" FOREIGN KEY ("station_id") REFERENCES "stations"("wu_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "daily_data" ADD CONSTRAINT "daily_data_station_id_stations_wu_id_fkey" FOREIGN KEY ("station_id") REFERENCES "stations"("wu_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "historical_stats" ADD CONSTRAINT "historical_stats_station_id_stations_wu_id_fkey" FOREIGN KEY ("station_id") REFERENCES "stations"("wu_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "hourly_data" ADD CONSTRAINT "hourly_data_station_id_stations_wu_id_fkey" FOREIGN KEY ("station_id") REFERENCES "stations"("wu_id") ON DELETE CASCADE;--> statement-breakpoint
ALTER TABLE "stats" ADD CONSTRAINT "stats_station_id_stations_wu_id_fkey" FOREIGN KEY ("station_id") REFERENCES "stations"("wu_id") ON DELETE CASCADE;
